### ISSUE TITLE
Unable to resolve action `sudo-bot/action-scrutinizer@latest`

### ISSUE THREAD

**Issue by ozh** [sudo-bot/action-scrutinizer#1]
Hi there,

Didn't change anything in my workflows but suddenly all jobs fail because:

>  Unable to resolve action `sudo-bot/action-scrutinizer@latest`, unable to find version `latest`

Example: https://github.com/YOURLS/YOURLS/actions/runs/1973700948

Thanks in advance!

**Comment by williamdes** [comment]
Hi @ozh !
I am sorry for this and really apologize, It seems like I did a mistake and deleted my git tag.
Should be okay now, have a great day and thank you for using my action !
