### ISSUE TITLE
The action doesn't work anymore

### ISSUE THREAD

**Issue by villfa** [sudo-bot/action-scrutinizer#2]
Hi,

Since 5526a35c3e86b8522300489790a555fc29e6f251 the action doesn't work anymore.

It fails with this error message:
```
  [Guzzle\Common\Exception\InvalidArgumentException]  
  Invalid handle provided
```

The problem is that `ocular.phar` uses an old version of Guzzle (3.7.3) while it supports PHP 8 since the [version 7.2.0](https://github.com/guzzle/guzzle/blob/7.2.0/CHANGELOG.md).

@williamdes would you agree to rollback your last change?

**Comment by villfa** [comment]
Another solution could be to install ocular with composer, but it would require more work.
See https://github.com/scrutinizer-ci/ocular/issues/54#issuecomment-784993370

**Comment by williamdes** [comment]
> Another solution could be to install ocular with composer, but it would require more work.
> See https://github.com/scrutinizer-ci/ocular/issues/54#issuecomment-784993370

Thank you for the great idea, I will probably do that as it will be more up to date

**Comment by williamdes** [comment]
It should be okay, please let me know if it is solved.
I apologize that my tests did not detect that, I will have to add more of them

**Comment by williamdes** [comment]
Just pushed c375a69a556481a1f51cae48e67e9be5c2088363 and the CI is green and the docker images are pushed

**Comment by villfa** [comment]
It works, thanks!

But I had to update the step with `actions/checkout` by setting a value to `fetch-depth`, otherwise it failed with this message:
```
In RepositoryIntrospector.php line 39:
                                                                               
  Failed to retrieve commit parents. If you use a shallow git checkout, pleas  
  e checkout at least a depth of one.    
```

You can take a look there: https://github.com/phpDocumentor/FlyFinder/pull/52

So I think it would be helpful to update the examples from your README as well.

**Comment by williamdes** [comment]
Let me know if 07cbb2ab4e236ab18d0eb3b2c35d2e2ad8d63b70 is fine

Merci

**Comment by villfa** [comment]
LGTM

Thanks again, for your work and your reactivity :)

**Comment by williamdes** [comment]
Bonjour @villfa 
I just changed to `10` the commit fetch depth and it worked fine !
For very large repos this is a better choice, so I will update the README accordingly 
https://github.com/phpmyadmin/phpmyadmin/runs/5712142532?check_suite_focus=true#step:12:10
