### ISSUE TITLE
It uses the wrong repository name (?)

### ISSUE THREAD

**Issue by mindplay-dk** [sudo-bot/action-scrutinizer#3]
Any idea why it appears to be using the wrong repository name?

https://github.com/mindplay-dk/sql/actions/runs/9266473142/job/25490784648

At the end of the workflow, it prints:

```
Notifying that no code coverage data is available for repository "g/mindplay-dk/sql" and revision "64ea0622e11404cfd1dd9bdf4597a8ffc86d0eb6"... Done
```

The repository name `g/mindplay-dk/sql` seems wrong? not a valid Github repository name, as far as I can tell?

I also tried with the additional `--revision=${{ github.event.pull_request.head.sha || github.sha }}` in `cli-args`, which seems to make no difference. (and the readme doesn't really explain what this is for?)

I checked, and there is definitely a code coverage report in `test/build/clover.xml` after running - for some reason, it's not seeing it, even though I've specified the path via `cli-args`?

**Comment by mindplay-dk** [comment]
ehm, it seems to have fixed itself? no idea what I changed or why. 🙈

**Comment by williamdes** [comment]
Thanks for reporting this, even if it was solved quicker than me replying 😸
